apiVersion: apps/v1
kind: Deployment
metadata:
  name: sudoku
  namespace: sudoku

spec:
  replicas: 2

  selector:
    matchLabels:
      app: sudoku

  template:
    metadata:
      labels:
        app: sudoku

    spec:
      containers:
        - name: sudoku
          image: docker.io/veeramattareddy/sudoko-game:6683108899b50eaa148983e7df26c6b06802f69a
          imagePullPolicy: Always

          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: 100m
              memory: 64Mi

            limits:
              cpu: 500m
              memory: 256Mi
