apiVersion: apps/v1
kind: Deployment
metadata:
  name: sudoku
  namespace: sudoku
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sudoku
  template:
    metadata:
      labels:
        app: sudoku
    spec:
      containers:
        - name: sudoku
        image: docker.io/veeramattareddy/sudoko-game:4be7e0fa302b9ad6300e45932b1a570f7d7497e1
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
